# Site settings
title: KMx404's portfolio
description: A Mohamed E.Faleh portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KMx404
user_description: Hello there, My name is Mohamed E.Faleh AKA KMx404. And this is my portfolio displaying some of my latest projects.
user_title: Software Developer
email: mohamedelfaleh5@gmail.com
twitter_username: KMx404
github_username:  KMx404
facebook_username:  KMx404

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
